import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { selectUser } from "../redux/userSlice";
import Home from "../components/Home";
import { useSelector } from "react-redux";
import Logout from "../components/Logout";
import Link from "next/link";
import Login from "./login";

export default function HomePage() {
	const user = useSelector(selectUser);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Login/>
			{/* <div>{user ? <Home /> : <Link href="/"/> }</div>; */}
		</div>
	);
}
